namespace Lumora.Privacy.NetworkBlocker;

// Domains bloqués dès le premier lancement, avant téléchargement des listes.
// Choix conservateur : uniquement des domaines dédiés à la pub/tracking, pas de services mixtes.
internal static class SeedList
{
    internal static readonly string[] Domains =
    [
        // ── Google advertising ────────────────────────────────────────────────
        "doubleclick.net",
        "googleadservices.com",
        "googlesyndication.com",
        "google-analytics.com",
        "googletagmanager.com",
        "googletagservices.com",
        "adservice.google.com",
        "pagead2.googlesyndication.com",
        "stats.g.doubleclick.net",
        "cm.g.doubleclick.net",
        "ad.doubleclick.net",

        // ── Meta / Facebook ───────────────────────────────────────────────────
        "connect.facebook.net",
        "pixel.facebook.com",
        "an.facebook.com",
        "graph.facebook.com",
        "edge.quantserve.com",

        // ── Programmatic ad networks ──────────────────────────────────────────
        "adnxs.com",
        "appnexus.com",
        "advertising.com",
        "yieldmanager.com",
        "ads.yahoo.com",
        "adserver.yahoo.com",
        "pubmatic.com",
        "rubiconproject.com",
        "openx.net",
        "openx.com",
        "33across.com",
        "criteo.com",
        "criteo.net",
        "taboola.com",
        "trc.taboola.com",
        "cdn.taboola.com",
        "outbrain.com",
        "revcontent.com",
        "mgid.com",
        "zedo.com",
        "adtechus.com",
        "smartadserver.com",
        "sas.smartadserver.com",
        "adsrvr.org",
        "casalemedia.com",
        "indexexchange.com",
        "liveintent.com",
        "sovrn.com",
        "undertone.com",
        "teads.tv",
        "sharethrough.com",
        "media.net",
        "contextweb.com",
        "bidswitch.net",
        "yieldmo.com",
        "spotxchange.com",
        "spotxchange.net",
        "mediamath.com",
        "adroll.com",
        "perfectmarket.com",
        "zemanta.com",
        "nativo.com",
        "conversantmedia.com",
        "addthis.com",
        "sharethis.com",
        "rhythmone.com",
        "adsystem.com",
        "mopub.com",
        "ads.twitter.com",
        "atdmt.com",
        "2mdn.net",
        "nexac.com",
        "yieldoptimizer.com",
        "bidsystem.com",
        "lijit.com",

        // ── Analytics & user tracking ─────────────────────────────────────────
        "scorecardresearch.com",
        "quantserve.com",
        "chartbeat.com",
        "chartbeat.net",
        "hotjar.com",
        "static.hotjar.com",
        "vars.hotjar.com",
        "mixpanel.com",
        "api.mixpanel.com",
        "amplitude.com",
        "api2.amplitude.com",
        "cdn.segment.com",
        "api.segment.io",
        "heapanalytics.com",
        "cdn.heapanalytics.com",
        "fullstory.com",
        "rs.fullstory.com",
        "pendo.io",
        "app.pendo.io",
        "cdn.pendo.io",
        "optimizely.com",
        "cdn.optimizely.com",
        "vwo.com",
        "dev.visualwebsiteoptimizer.com",
        "sessioncam.com",
        "mouseflow.com",
        "clicktale.com",
        "crazyegg.com",
        "luckyorange.com",
        "inspectlet.com",
        "logrocket.io",
        "r.logrocket.io",
        "usabilla.com",
        "siteintercept.qualtrics.com",

        // ── Audience & data management platforms ──────────────────────────────
        "bluekai.com",
        "bluekai-dmz.com",
        "krxd.net",
        "crwdcntrl.net",
        "demdex.net",
        "dmtry.com",
        "tiqcdn.com",
        "tags.tiqcdn.com",
        "tapad.com",
        "onaudience.com",
        "adkernel.com",
        "bkrtx.com",
        "sizmek.com",
        "rlcdn.com",
        "imrworldwide.com",

        // ── Email marketing trackers ──────────────────────────────────────────
        "tracking.sendgrid.net",
        "click.sendgrid.net",
        "track.mailerlite.com",
        "tracking.activecampaign.com",

        // ── Performance monitoring (télémétrie vers tiers) ────────────────────
        "nr-data.net",
        "bam.nr-data.net",
        "beacon.krxd.net",

        // ── Adobe analytics ───────────────────────────────────────────────────
        "omtrdc.net",
        "2o7.net",
        "adobedtm.com",
        "demdex.net",

        // ── Autres trackers fréquents ─────────────────────────────────────────
        "4stats.de",
        "99stats.com",
        "a-ads.com",
        "aax-us-east.amazon-adsystem.com",
        "amazon-adsystem.com",
        "adsystem.amazon.com",
        "adservice.google.co.uk",
        "adservice.google.fr",
        "adservice.google.de",
        "adservice.google.ca",
        "adservice.google.com.au",
    ];
}
